apiVersion: v1
kind: ReplicationController
metadata:
  name: tf-worker0
spec:
  replicas: 1
  template:
    metadata:
      labels:
        tf-worker: "0"
        name-prefix: "tf"
        job: "worker"
    spec:
      containers:
      - name: tf-worker0
        image: 192.168.1.201:5000/laojun/test:develop06
        args: ["--task_id=0", "--job_name=worker", "--cluster_spec=worker|tf-worker0:2222;tf-worker1:2222;tf-worker2:2222;tf-worker3:2222;tf-worker4:2222;tf-worker5:2222,ps|tf-ps0:2222;tf-ps1:2222"]
        ports:
        - containerPort: 2222
        env: []
        volumeMounts: [{name: shared, mountPath: /shared}]
      volumes: [{name: shared, hostPath: {path: /shared}}]
---
apiVersion: v1
kind: Service
metadata:
  name: tf-worker0
  labels:
    tf-worker: "0"
spec:
  type: LoadBalancer
  ports:
  - port: 2222
  selector:
    tf-worker: "0"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: tf-worker1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        tf-worker: "1"
        name-prefix: "tf"
        job: "worker"
    spec:
      containers:
      - name: tf-worker1
        image: 192.168.1.201:5000/laojun/test:develop06
        args: ["--task_id=1", "--job_name=worker", "--cluster_spec=worker|tf-worker0:2222;tf-worker1:2222;tf-worker2:2222;tf-worker3:2222;tf-worker4:2222;tf-worker5:2222,ps|tf-ps0:2222;tf-ps1:2222"]
        ports:
        - containerPort: 2222
        env: []
        volumeMounts: [{name: shared, mountPath: /shared}]
      volumes: [{name: shared, hostPath: {path: /shared}}]
---
apiVersion: v1
kind: Service
metadata:
  name: tf-worker1
  labels:
    tf-worker: "1"
spec:
  type: LoadBalancer
  ports:
  - port: 2222
  selector:
    tf-worker: "1"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: tf-worker2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        tf-worker: "2"
        name-prefix: "tf"
        job: "worker"
    spec:
      containers:
      - name: tf-worker2
        image: 192.168.1.201:5000/laojun/test:develop06
        args: ["--task_id=2", "--job_name=worker", "--cluster_spec=worker|tf-worker0:2222;tf-worker1:2222;tf-worker2:2222;tf-worker3:2222;tf-worker4:2222;tf-worker5:2222,ps|tf-ps0:2222;tf-ps1:2222"]
        ports:
        - containerPort: 2222
        env: []
        volumeMounts: [{name: shared, mountPath: /shared}]
      volumes: [{name: shared, hostPath: {path: /shared}}]
---
apiVersion: v1
kind: Service
metadata:
  name: tf-worker2
  labels:
    tf-worker: "2"
spec:
  type: LoadBalancer
  ports:
  - port: 2222
  selector:
    tf-worker: "2"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: tf-worker3
spec:
  replicas: 1
  template:
    metadata:
      labels:
        tf-worker: "3"
        name-prefix: "tf"
        job: "worker"
    spec:
      containers:
      - name: tf-worker3
        image: 192.168.1.201:5000/laojun/test:develop06
        args: ["--task_id=3", "--job_name=worker", "--cluster_spec=worker|tf-worker0:2222;tf-worker1:2222;tf-worker2:2222;tf-worker3:2222;tf-worker4:2222;tf-worker5:2222,ps|tf-ps0:2222;tf-ps1:2222"]
        ports:
        - containerPort: 2222
        env: []
        volumeMounts: [{name: shared, mountPath: /shared}]
      volumes: [{name: shared, hostPath: {path: /shared}}]
---
apiVersion: v1
kind: Service
metadata:
  name: tf-worker3
  labels:
    tf-worker: "3"
spec:
  type: LoadBalancer
  ports:
  - port: 2222
  selector:
    tf-worker: "3"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: tf-worker4
spec:
  replicas: 1
  template:
    metadata:
      labels:
        tf-worker: "4"
        name-prefix: "tf"
        job: "worker"
    spec:
      containers:
      - name: tf-worker4
        image: 192.168.1.201:5000/laojun/test:develop06
        args: ["--task_id=4", "--job_name=worker", "--cluster_spec=worker|tf-worker0:2222;tf-worker1:2222;tf-worker2:2222;tf-worker3:2222;tf-worker4:2222;tf-worker5:2222,ps|tf-ps0:2222;tf-ps1:2222"]
        ports:
        - containerPort: 2222
        env: []
        volumeMounts: [{name: shared, mountPath: /shared}]
      volumes: [{name: shared, hostPath: {path: /shared}}]
---
apiVersion: v1
kind: Service
metadata:
  name: tf-worker4
  labels:
    tf-worker: "4"
spec:
  type: LoadBalancer
  ports:
  - port: 2222
  selector:
    tf-worker: "4"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: tf-worker5
spec:
  replicas: 1
  template:
    metadata:
      labels:
        tf-worker: "5"
        name-prefix: "tf"
        job: "worker"
    spec:
      containers:
      - name: tf-worker5
        image: 192.168.1.201:5000/laojun/test:develop06
        args: ["--task_id=5", "--job_name=worker", "--cluster_spec=worker|tf-worker0:2222;tf-worker1:2222;tf-worker2:2222;tf-worker3:2222;tf-worker4:2222;tf-worker5:2222,ps|tf-ps0:2222;tf-ps1:2222"]
        ports:
        - containerPort: 2222
        env: []
        volumeMounts: [{name: shared, mountPath: /shared}]
      volumes: [{name: shared, hostPath: {path: /shared}}]
---
apiVersion: v1
kind: Service
metadata:
  name: tf-worker5
  labels:
    tf-worker: "5"
spec:
  type: LoadBalancer
  ports:
  - port: 2222
  selector:
    tf-worker: "5"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: tf-ps0
spec:
  replicas: 1
  template:
    metadata:
      labels:
        tf-ps: "0"
        name-prefix: "tf"
        job: "ps"
    spec:
      containers:
      - name: tf-ps0
        image: 192.168.1.201:5000/laojun/test:develop06
        args: ["--task_id=0", "--job_name=ps", "--cluster_spec=worker|tf-worker0:2222;tf-worker1:2222;tf-worker2:2222;tf-worker3:2222;tf-worker4:2222;tf-worker5:2222,ps|tf-ps0:2222;tf-ps1:2222"]
        ports:
        - containerPort: 2222
        env: []
        volumeMounts: [{name: shared, mountPath: /shared}]
      volumes: [{name: shared, hostPath: {path: /shared}}]
---
apiVersion: v1
kind: Service
metadata:
  name: tf-ps0
  labels:
    tf-ps: "0"
spec:
  type: LoadBalancer
  ports:
  - port: 2222
  selector:
    tf-ps: "0"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: tf-ps1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        tf-ps: "1"
        name-prefix: "tf"
        job: "ps"
    spec:
      containers:
      - name: tf-ps1
        image: 192.168.1.201:5000/laojun/test:develop06
        args: ["--task_id=1", "--job_name=ps", "--cluster_spec=worker|tf-worker0:2222;tf-worker1:2222;tf-worker2:2222;tf-worker3:2222;tf-worker4:2222;tf-worker5:2222,ps|tf-ps0:2222;tf-ps1:2222"]
        ports:
        - containerPort: 2222
        env: []
        volumeMounts: [{name: shared, mountPath: /shared}]
      volumes: [{name: shared, hostPath: {path: /shared}}]
---
apiVersion: v1
kind: Service
metadata:
  name: tf-ps1
  labels:
    tf-ps: "1"
spec:
  type: LoadBalancer
  ports:
  - port: 2222
  selector:
    tf-ps: "1"
---

